### ISSUE TITLE
How to change the eventcell's color?

### ISSUE THREAD

**Issue by ssiang1627** [BadChoice/RVCalendarWeekView#24]
How to change the eventcell's color?
I want to change the color of the selected one and the unselected one

**Comment by BadChoice** [comment]
You should subclass it and then use your one.

to use your one, you need to sublclass `weekview` as well and simply call

```
    -(void)setupSupplementaryViewClasses{ [super
         setupSupplementaryViewClasses]; self.eventCellClass = MyNewEventCell.class;
    } 
```


Encès 12 de desembre de 2016 a 15:21:34, 102306051林聖翔 (
notifications@github.com) va escriure:

How to change the eventcell's color?
I want to change the color of the selected one and the unselected one

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BadChoice/RVCalendarWeekView/issues/24>, or mute the
thread
